server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=FALSE&serverTimezone=UTC
    username: root
    password: 111
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com:
      example:
        security20220728afternoon:
    .mapper: debug  # ??sql??

